name: Create and publish the Docker image

on: 
  workflow_dispatch:
    inputs:
      binutilsVersion:
        description: 'binutils-gdb version'     
        required: true
        default: '2.38'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: datadog/binutils-gdb
  IMAGE_TAG: ${{ github.event.inputs.binutilsVersion }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=${{ github.event.inputs.binutilsVersion }}
